apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
      include: '*.yaml'
    repoURL: https://github.com/codefresh-contrib/kubecon-eu-2023-demo-crossplane-vcluster.git
    targetRevision: HEAD
    path: crossplane-resources
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true